=== zachwong02/zachwong02.github.io/.astro/collections/socials.schema.json
{
  "$ref": "#/definitions/socials",
  "definitions": {
    "socials": {
      "type": "object",
      "properties": {
        "id": {
          "type": "number"
        },
        "icon": {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "const": "lucide"
                },
                "name": {}
              },
              "required": [
                "type"
              ],
              "additionalProperties": false
            },
            {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "const": "simple-icons"
                },
                "name": {}
              },
              "required": [
                "type"
              ],
              "additionalProperties": false
            }
          ]
        },
        "text": {
          "type": "string"
        },
        "link": {
          "type": "string",
          "format": "uri"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "icon",
        "text",
        "link"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== zachwong02/zachwong02.github.io/src/content/socials.json
[
  {
    "id": 1,
    "icon": {
      "type": "lucide",
      "name": "github"
    },
    "text": "GitHub",
    "link": "https://github.com/zachwong02"
  },
  {
    "id": 2,
    "icon": {
      "type": "lucide",
      "name": "linkedin"
    },
    "text": "LinkedIn",
    "link": "https://www.linkedin.com/in/zachwong02/"
  }
]
